### ISSUE TITLE
Stalled requests

### ISSUE THREAD

**Issue by samtietjen** [payloadcms/next-payload-demo#1]
I noticed things were a bit slow so I checked out the console and saw this:
```
API resolved without sending a response for /api/_preferences/collapsed-Collections-groups, this may result in stalled requests.
API resolved without sending a response for /api/_preferences/collapsed-Globals-groups, this may result in stalled requests.
API resolved without sending a response for /api/users/init, this may result in stalled requests.
API resolved without sending a response for /api/users/me, this may result in stalled requests.
```
Any idea what's up here? /api/users seems global, while /api/_preferences/ is in the admin only.

**Comment by rbnams** [comment]
Same here, did you find a solution yet?

**Comment by jmikrut** [comment]
Wellllll, that warning message is on our radar to fix, but I think it's not exactly legit. If you look at the handler code for those endpoints, they clearly _**do**_ send responses. We should have answers for this shortly.

I think the slowness you're seeing in dev is a result of each endpoint having to compile in dev mode, and in prod, it's a result of serverless cold starts. I think we can also improve a bit of the cold start issue, but not sure how much we can do about the dev endpoints needing to compile. 

Regardless, I will post back with a bit more info here in a bit!

**Comment by jmikrut** [comment]
Hey @culicom and @samtietjen we've just looked into this extensively and were able to fix the warnings, but there are still cold start times to deal with. 

There's little we can do at this point unfortunately as it seems like slow cold starts are a pretty common issue with Vercel API routes in general. We will be moving to edge functions as soon as we can, but for now, if slow starts are a concern, we'd suggest Payload Cloud instead. 

Does that make sense?
