### ISSUE TITLE
Integration with t3 stack

### ISSUE THREAD

**Issue by krisgrm** [payloadcms/next-payload-demo#2]
I'd love to see if we could make this work https://github.com/t3-oss/create-t3-turbo

**Comment by jmikrut** [comment]
Hey @krisgrm — I'm sure it could. There are a few people in our Discord asking about T3. You are free to use Tailwind with this repo just like you would with any other Next app, but the harder part will be bringing in tRPC. 

In that case, adding tRPC support would be done inside of Payload. Maybe you could get a conversation going in the Payload discussions about that, and we'll see what we can do!
