### ISSUE TITLE
Error on Vercel

### ISSUE THREAD

**Issue by arunkp** [payloadcms/next-payload-demo#7]
Deployed to Vercel as a test and we have an issue with the payload package. Any idea why?

<img width="1775" alt="Screenshot 2023-07-08 at 23 09 49" src="https://github.com/payloadcms/next-payload-demo/assets/4560500/4b8c1b0e-1daf-4b00-8f9d-1740c881d088">

**Comment by jmikrut** [comment]
Hey there! Are you importing Payload's `Label` component anywhere in your code? Or do you have any plugins installed? 

You need to add `'use client'` to the top of any of your config files / components that import SCSS. That will fix this. 👍

**Comment by arunkp** [comment]
I think i solved it. I started a fresh nextjs project and add the next-payload plugin. I had a different issue with the plugin, it was unable to find the payload config since i had moved it inside `src`, thats the reason i wanted to test with payload-demo repo. But i think it solved my problem. Thank you for the quick response 🙏🏼
